// Goal constants

export const GET_ALL_PLAYLIST = "playlist/GET_ALL_PLAYLIST";
export const GET_ALL_PLAYLIST_ACTION = "playlist/GET_ALL_PLAYLIST_ACTION";
export const SET_ALL_PLAYLIST = "playlist/SET_ALL_PLAYLIST";

export const GET_PLAYLIST_DETAIL = "playlist/GET_PLAYLIST_DETAIL";
export const GET_PLAYLIST_DETAIL_ACTION = "playlist/GET_PLAYLIST_DETAIL_ACTION";
export const SET_PLAYLIST_DETAIL = "playlist/SET_PLAYLIST_DETAIL";

export const CREATE_PLAYLIST_ACTION = "playlist/CREATE_PLAYLIST_ACTION";
export const UPDATE_PLAYLIST_ACTION = "playlist/UPDATE_PLAYLIST_ACTION";
export const DELETE_PLAYLIST_ACTION = "playlist/DELETE_PLAYLIST_ACTION";
